// AUTO-GENERATED by scripts/build-subtitle-content.ts — DO NOT EDIT
import type { BundleConfig } from '../../../types/bundle';

export const config: BundleConfig = {
  id: 'himym-s01-es',
  type: 'builtin',
  nativeLanguage: 'Deutsch',
  targetLanguage: 'Español',
  displayLabel: 'Deutsch → Español',
  greetings: {
    morning: 'Buenos días',
    afternoon: 'Buenas tardes',
    evening: 'Buenas noches',
  },
  motivational: {
    perfect: '¡Perfecto!',
    great: '¡Muy bien!',
    good: '¡Bien hecho!',
    encouragement: '¡Sigue así!',
  },
  spellCharacters: 'abcdefghijklmnopqrstuvwxyzáéíóúüñ¿¡'.split(''),
  searchPlaceholder: 'Suche auf Spanisch oder Deutsch...',
};
