// AUTO-GENERATED by scripts/build-content.ts — DO NOT EDIT
import type { BundleConfig } from '../../../types/bundle';

export const config: BundleConfig = {
  id: 'hu-de-budapest',
  type: 'builtin',
  nativeLanguage: 'Deutsch',
  targetLanguage: 'Magyar',
  displayLabel: 'Deutsch → Magyar',
  greetings: {
    morning: 'Jó reggelt',
    afternoon: 'Jó napot',
    evening: 'Jó estét',
  },
  motivational: {
    perfect: 'Tökéletes!',
    great: 'Nagyon jó!',
    good: 'Jó munka!',
    encouragement: 'Csak így tovább!',
  },
  spellCharacters: 'abcdefghijklmnopqrstuvwxyzáéíóöőúüű'.split(''),
  searchPlaceholder: 'Search Magyar or Deutsch...',
};
